# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/framework/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/framework/proprietary/etc/permissions/com.sony.device.xml:system/etc/permissions/com.sony.device.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sony.snei.vu.xml:system/etc/permissions/com.sony.snei.vu.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sony.sysinfo.xml:system/etc/permissions/com.sony.sysinfo.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.android.bootinfoif.xml:system/etc/permissions/com.sonyericsson.android.bootinfoif.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.android.omacp.xml:system/etc/permissions/com.sonyericsson.android.omacp.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.android.semcrilextension.xml:system/etc/permissions/com.sonyericsson.android.semcrilextension.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.android.socialphonebook.xml:system/etc/permissions/com.sonyericsson.android.socialphonebook.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.appextensions.xml:system/etc/permissions/com.sonyericsson.appextensions.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.autopoweroff.xml:system/etc/permissions/com.sonyericsson.autopoweroff.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.bluetooth.a2dp.xml:system/etc/permissions/com.sonyericsson.bluetooth.a2dp.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.cameraextension.xml:system/etc/permissions/com.sonyericsson.cameraextension.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.dlna.dtcpplayer.xml:system/etc/permissions/com.sonyericsson.dlna.dtcpplayer.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.dlna.playanywhere.xml:system/etc/permissions/com.sonyericsson.dlna.playanywhere.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.idd.xml:system/etc/permissions/com.sonyericsson.idd.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.illumination.xml:system/etc/permissions/com.sonyericsson.illumination.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.media.infinite.extension_1.xml:system/etc/permissions/com.sonyericsson.media.infinite.extension_1.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.metadatacleanup.xml:system/etc/permissions/com.sonyericsson.metadatacleanup.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.mimetype.xml:system/etc/permissions/com.sonyericsson.mimetype.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.musicvisualizer.xml:system/etc/permissions/com.sonyericsson.musicvisualizer.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.privateapis.xml:system/etc/permissions/com.sonyericsson.privateapis.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.sysmon.xml:system/etc/permissions/com.sonyericsson.sysmon.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.system.xml:system/etc/permissions/com.sonyericsson.system.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.updatecenter.xml:system/etc/permissions/com.sonyericsson.updatecenter.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.video.player.service.xml:system/etc/permissions/com.sonyericsson.video.player.service.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonyericsson.video.settings.xml:system/etc/permissions/com.sonyericsson.video.settings.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.album.xml:system/etc/permissions/com.sonymobile.album.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.bluetoothunlock.api.xml:system/etc/permissions/com.sonymobile.bluetoothunlock.api.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.callwidgetframework.xml:system/etc/permissions/com.sonymobile.callwidgetframework.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.camera.addon.xml:system/etc/permissions/com.sonymobile.camera.addon.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.cityid.common.xml:system/etc/permissions/com.sonymobile.cityid.common.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.covermode.xml:system/etc/permissions/com.sonymobile.covermode.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.datawasher.xml:system/etc/permissions/com.sonymobile.datawasher.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.devicesecurity.xml:system/etc/permissions/com.sonymobile.devicesecurity.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.drm.dtcp.xml:system/etc/permissions/com.sonymobile.drm.dtcp.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.drm.restriction.xml:system/etc/permissions/com.sonymobile.drm.restriction.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.drmstream.xml:system/etc/permissions/com.sonymobile.drmstream.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.enterprise.xml:system/etc/permissions/com.sonymobile.enterprise.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.extendedbootlock.xml:system/etc/permissions/com.sonymobile.extendedbootlock.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.facebook.proxy.api.xml:system/etc/permissions/com.sonymobile.facebook.proxy.api.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.faceeditor.xml:system/etc/permissions/com.sonymobile.faceeditor.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.home.resourceprovider.xml:system/etc/permissions/com.sonymobile.home.resourceprovider.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.imageprocessor.xml:system/etc/permissions/com.sonymobile.imageprocessor.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.locationhistory.xml:system/etc/permissions/com.sonymobile.locationhistory.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.media.dashboard.extension.xml:system/etc/permissions/com.sonymobile.media.dashboard.extension.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.mediacontent.xml:system/etc/permissions/com.sonymobile.mediacontent.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.mirrorpowersave.xml:system/etc/permissions/com.sonymobile.mirrorpowersave.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.miscta.xml:system/etc/permissions/com.sonymobile.miscta.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.musicslideshow.xml:system/etc/permissions/com.sonymobile.musicslideshow.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.photoanalyzer.xml:system/etc/permissions/com.sonymobile.photoanalyzer.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.photoeditor.xml:system/etc/permissions/com.sonymobile.photoeditor.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.playanywhere.xml:system/etc/permissions/com.sonymobile.playanywhere.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.podcast.xml:system/etc/permissions/com.sonymobile.podcast.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.provider.tasks.xml:system/etc/permissions/com.sonymobile.provider.tasks.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.providers.extendedcalllog.xml:system/etc/permissions/com.sonymobile.providers.extendedcalllog.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.remotefileaccess.xml:system/etc/permissions/com.sonymobile.remotefileaccess.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.runtimeskinning.xml:system/etc/permissions/com.sonymobile.runtimeskinning.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.servicemenu.xml:system/etc/permissions/com.sonymobile.servicemenu.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.settings.illumination.xml:system/etc/permissions/com.sonymobile.settings.illumination.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.settings.logging.xml:system/etc/permissions/com.sonymobile.settings.logging.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.settings.shakecontrol.xml:system/etc/permissions/com.sonymobile.settings.shakecontrol.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.simlock.platform.xml:system/etc/permissions/com.sonymobile.simlock.platform.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.softreset.xml:system/etc/permissions/com.sonymobile.softreset.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.telephonyinformation.common.xml:system/etc/permissions/com.sonymobile.telephonyinformation.common.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.tlextract.xml:system/etc/permissions/com.sonymobile.tlextract.xml \
    vendor/sony/framework/proprietary/etc/permissions/com.sonymobile.trackid.xml:system/etc/permissions/com.sonymobile.trackid.xml \
    vendor/sony/framework/proprietary/framework/com.sony.device.jar:system/framework/com.sony.device.jar \
    vendor/sony/framework/proprietary/framework/com.sony.snei.vu.jar:system/framework/com.sony.snei.vu.jar \
    vendor/sony/framework/proprietary/framework/com.sony.sysinfo.jar:system/framework/com.sony.sysinfo.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.android.omacp.jar:system/framework/com.sonyericsson.android.omacp.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.android.socialphonebook.dynamic.jar:system/framework/com.sonyericsson.android.socialphonebook.dynamic.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.appextensions.jar:system/framework/com.sonyericsson.appextensions.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.autopoweroff.jar:system/framework/com.sonyericsson.autopoweroff.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.bluetooth.a2dp.jar:system/framework/com.sonyericsson.bluetooth.a2dp.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.cameraextension_impl.jar:system/framework/com.sonyericsson.cameraextension_impl.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.dlna.dtcpplayer.jar:system/framework/com.sonyericsson.dlna.dtcpplayer.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.dlna.playanywhere.jar:system/framework/com.sonyericsson.dlna.playanywhere.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.idd.jar:system/framework/com.sonyericsson.idd.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.illumination.jar:system/framework/com.sonyericsson.illumination.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.media.infinite.extension_1.jar:system/framework/com.sonyericsson.media.infinite.extension_1.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.metadatacleanup.jar:system/framework/com.sonyericsson.metadatacleanup.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.mimetype.jar:system/framework/com.sonyericsson.mimetype.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.music.jar:system/framework/com.sonyericsson.music.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.musicvisualizer.jar:system/framework/com.sonyericsson.musicvisualizer.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.privateapis_impl.jar:system/framework/com.sonyericsson.privateapis_impl.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.sysmon.jar:system/framework/com.sonyericsson.sysmon.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.system.jar:system/framework/com.sonyericsson.system.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.updatecenter.jar:system/framework/com.sonyericsson.updatecenter.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.video.jar:system/framework/com.sonyericsson.video.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.video.player.service.jar:system/framework/com.sonyericsson.video.player.service.jar \
    vendor/sony/framework/proprietary/framework/com.sonyericsson.video.settings.jar:system/framework/com.sonyericsson.video.settings.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.album.jar:system/framework/com.sonymobile.album.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.bluetoothunlock.api.jar:system/framework/com.sonymobile.bluetoothunlock.api.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.callwidgetframework.jar:system/framework/com.sonymobile.callwidgetframework.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.camera.addon_impl.jar:system/framework/com.sonymobile.camera.addon_impl.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.cityid.common.jar:system/framework/com.sonymobile.cityid.common.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.covermode.jar:system/framework/com.sonymobile.covermode.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.datawasher.jar:system/framework/com.sonymobile.datawasher.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.devicesecurity_impl.jar:system/framework/com.sonymobile.devicesecurity_impl.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.drm.dtcp.jar:system/framework/com.sonymobile.drm.dtcp.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.drm.restriction.jar:system/framework/com.sonymobile.drm.restriction.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.ds4.jar:system/framework/com.sonymobile.ds4.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.dtcp.remoteaccessregisterapi.jar:system/framework/com.sonymobile.dtcp.remoteaccessregisterapi.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.facebook.proxy.api.jar:system/framework/com.sonymobile.facebook.proxy.api.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.faceeditor.jar:system/framework/com.sonymobile.faceeditor.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.home.resourceprovider.jar:system/framework/com.sonymobile.home.resourceprovider.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.imageprocessor.jpegdecoder_impl.jar:system/framework/com.sonymobile.imageprocessor.jpegdecoder_impl.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.imageprocessor.jpegencoder_impl.jar:system/framework/com.sonymobile.imageprocessor.jpegencoder_impl.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.imageprocessor.superresolution_impl.jar:system/framework/com.sonymobile.imageprocessor.superresolution_impl.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.locationhistory.jar:system/framework/com.sonymobile.locationhistory.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.media.dashboard.extension.jar:system/framework/com.sonymobile.media.dashboard.extension.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.mediacontent.jar:system/framework/com.sonymobile.mediacontent.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.miscta_impl.jar:system/framework/com.sonymobile.miscta_impl.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.musicslideshow.jar:system/framework/com.sonymobile.musicslideshow.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.photoanalyzer.jar:system/framework/com.sonymobile.photoanalyzer.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.photoanalyzer_impl.jar:system/framework/com.sonymobile.photoanalyzer_impl.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.photoeditor.jar:system/framework/com.sonymobile.photoeditor.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.playanywhere.jar:system/framework/com.sonymobile.playanywhere.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.podcast.jar:system/framework/com.sonymobile.podcast.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.provider.tasks.jar:system/framework/com.sonymobile.provider.tasks.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.remotefileaccess.jar:system/framework/com.sonymobile.remotefileaccess.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.runtimeskinning.jar:system/framework/com.sonymobile.runtimeskinning.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.servicemenu.jar:system/framework/com.sonymobile.servicemenu.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.settings.illumination.jar:system/framework/com.sonymobile.settings.illumination.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.settings.logging.jar:system/framework/com.sonymobile.settings.logging.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.settings.shakecontrol.jar:system/framework/com.sonymobile.settings.shakecontrol.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.simlock.platform.jar:system/framework/com.sonymobile.simlock.platform.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.softreset.jar:system/framework/com.sonymobile.softreset.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.tlextract.jar:system/framework/com.sonymobile.tlextract.jar \
    vendor/sony/framework/proprietary/framework/com.sonymobile.tvout.wifidisplay.jar:system/framework/com.sonymobile.tvout.wifidisplay.jar
